---
- name: provision two devstack nodes for neutron floodlight - common
  hosts:
    - controller
    - compute1
  user: vagrant
  gather_facts: False
  tasks:

  - name: install packages
    sudo: True
    apt:  name={{ item }} update_cache=yes
    with_items:
      - git
      - python-pip
      - language-pack-en-base
      - openvswitch-datapath-dkms
      - openvswitch-common
      - openvswitch-switch

    # workaround a dependency issue where 0.6.1 is installed, but devstack needs 0.7.2
  - pip: name=prettytable state=latest
    sudo: True

    # http://askubuntu.com/a/17002
  - command: dpkg-reconfigure locales
             creates=/home/vagrant/.reconfigure-locale-done
    sudo: True

  - command: git config --global color.ui true

  - name: git clone devstack
    git:  repo=https://github.com/openstack-dev/devstack
          dest=/home/vagrant/devstack force=no update=no

  - name: copy script for configuring openvswitch
    copy: src=ovs-init.sh dest=/home/vagrant/ovs-init.sh
          owner=vagrant group=vagrant mode=0755


- name: controller node
  hosts: controller
  user: vagrant
  gather_facts: False
  tasks:

  - name: install packages
    sudo: True
    apt:  name={{ item }}
    with_items:
      - default-jdk
      - ant

  - name: git clone floodlight
    git:  repo=https://github.com/floodlight/floodlight
          dest=/home/vagrant/floodlight version=fl-last-passed-build force=no update=no

  - name: copy localrc
    copy: src=localrc.controller dest=/home/vagrant/devstack/localrc
          force=no owner=vagrant group=vagrant mode=0644


- name: compute node
  hosts: compute1
  user: vagrant
  gather_facts: False
  tasks:

  - name: copy localrc
    copy: src=localrc.compute1 dest=/home/vagrant/devstack/localrc
          force=no owner=vagrant group=vagrant mode=0644
